services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    environment:
      - N8N_HOST=wsp-sticker-bot.duckdns.org
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://wsp-sticker-bot.duckdns.org/
      - GENERIC_TIMEZONE=America/Argentina/Buenos_Aires
    ports:
      - "127.0.0.1:5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    
volumes:
  n8n_data:
    external: true